/**
 * Enhanced Airport Database with Coordinates and Metadata
 * Provides comprehensive airport data including coordinates, timezones, and ICAO codes
 * for accurate distance calculations and flight validation
 */

export interface Airport {
  code: string; // IATA code (3 letters)
  icao: string; // ICAO code (4 letters)
  name: string;
  city: string;
  country: string;
  region: string;
  latitude: number; // Decimal degrees
  longitude: number; // Decimal degrees
  timezone: string; // IANA timezone identifier
  elevation?: number; // Elevation in feet
  isActive: boolean; // Whether airport is currently operational
  hubType?: 'major' | 'secondary' | 'regional' | 'domestic'; // Hub classification
}

// Major international airports with coordinates and metadata
export const airports: Airport[] = [
  // Major US Airports
  {
    code: 'ATL',
    icao: 'KATL',
    name: 'Hartsfield-Jackson Atlanta International',
    city: 'Atlanta',
    country: 'United States',
    region: 'North America',
    latitude: 33.6407,
    longitude: -84.4277,
    timezone: 'America/New_York',
    elevation: 1026,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LAX',
    icao: 'KLAX',
    name: 'Los Angeles International',
    city: 'Los Angeles',
    country: 'United States',
    region: 'North America',
    latitude: 33.9425,
    longitude: -118.4081,
    timezone: 'America/Los_Angeles',
    elevation: 125,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ORD',
    icao: 'KORD',
    name: "O'Hare International",
    city: 'Chicago',
    country: 'United States',
    region: 'North America',
    latitude: 41.9786,
    longitude: -87.9048,
    timezone: 'America/Chicago',
    elevation: 672,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DFW',
    icao: 'KDFW',
    name: 'Dallas/Fort Worth International',
    city: 'Dallas',
    country: 'United States',
    region: 'North America',
    latitude: 32.8968,
    longitude: -97.038,
    timezone: 'America/Chicago',
    elevation: 607,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DEN',
    icao: 'KDEN',
    name: 'Denver International',
    city: 'Denver',
    country: 'United States',
    region: 'North America',
    latitude: 39.8561,
    longitude: -104.6737,
    timezone: 'America/Denver',
    elevation: 5431,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'JFK',
    icao: 'KJFK',
    name: 'John F. Kennedy International',
    city: 'New York',
    country: 'United States',
    region: 'North America',
    latitude: 40.6413,
    longitude: -73.7781,
    timezone: 'America/New_York',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'SFO',
    icao: 'KSFO',
    name: 'San Francisco International',
    city: 'San Francisco',
    country: 'United States',
    region: 'North America',
    latitude: 37.6213,
    longitude: -122.379,
    timezone: 'America/Los_Angeles',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'SEA',
    icao: 'KSEA',
    name: 'Seattle-Tacoma International',
    city: 'Seattle',
    country: 'United States',
    region: 'North America',
    latitude: 47.4502,
    longitude: -122.3088,
    timezone: 'America/Los_Angeles',
    elevation: 433,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LAS',
    icao: 'KLAS',
    name: 'McCarran International',
    city: 'Las Vegas',
    country: 'United States',
    region: 'North America',
    latitude: 36.084,
    longitude: -115.1537,
    timezone: 'America/Los_Angeles',
    elevation: 2181,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MIA',
    icao: 'KMIA',
    name: 'Miami International',
    city: 'Miami',
    country: 'United States',
    region: 'North America',
    latitude: 25.7959,
    longitude: -80.287,
    timezone: 'America/New_York',
    elevation: 8,
    isActive: true,
    hubType: 'major',
  },

  // Major European Airports
  {
    code: 'LHR',
    icao: 'EGLL',
    name: 'London Heathrow',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.47,
    longitude: -0.4543,
    timezone: 'Europe/London',
    elevation: 83,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CDG',
    icao: 'LFPG',
    name: 'Charles de Gaulle',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    latitude: 49.0097,
    longitude: 2.5479,
    timezone: 'Europe/Paris',
    elevation: 392,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'AMS',
    icao: 'EHAM',
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    latitude: 52.3105,
    longitude: 4.7683,
    timezone: 'Europe/Amsterdam',
    elevation: -11,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'FRA',
    icao: 'EDDF',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    region: 'Europe',
    latitude: 50.0379,
    longitude: 8.5622,
    timezone: 'Europe/Berlin',
    elevation: 364,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MAD',
    icao: 'LEMD',
    name: 'Adolfo Suárez Madrid-Barajas',
    city: 'Madrid',
    country: 'Spain',
    region: 'Europe',
    latitude: 40.4983,
    longitude: -3.5676,
    timezone: 'Europe/Madrid',
    elevation: 2000,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BCN',
    icao: 'LEBL',
    name: 'Barcelona-El Prat',
    city: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    latitude: 41.2974,
    longitude: 2.0833,
    timezone: 'Europe/Madrid',
    elevation: 14,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'FCO',
    icao: 'LIRF',
    name: 'Leonardo da Vinci-Fiumicino',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    latitude: 41.8003,
    longitude: 12.2389,
    timezone: 'Europe/Rome',
    elevation: 15,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MUC',
    icao: 'EDDM',
    name: 'Munich Airport',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    latitude: 48.3538,
    longitude: 11.7861,
    timezone: 'Europe/Berlin',
    elevation: 1487,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ZUR',
    icao: 'LSZH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    latitude: 47.4647,
    longitude: 8.5492,
    timezone: 'Europe/Zurich',
    elevation: 1416,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'VIE',
    icao: 'LOWW',
    name: 'Vienna International',
    city: 'Vienna',
    country: 'Austria',
    region: 'Europe',
    latitude: 48.1103,
    longitude: 16.5697,
    timezone: 'Europe/Vienna',
    elevation: 600,
    isActive: true,
    hubType: 'major',
  },

  // Major Asian Airports
  {
    code: 'PEK',
    icao: 'ZBAA',
    name: 'Beijing Capital International',
    city: 'Beijing',
    country: 'China',
    region: 'Asia',
    latitude: 40.0799,
    longitude: 116.6031,
    timezone: 'Asia/Shanghai',
    elevation: 115,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'PVG',
    icao: 'ZSPD',
    name: 'Shanghai Pudong International',
    city: 'Shanghai',
    country: 'China',
    region: 'Asia',
    latitude: 31.1443,
    longitude: 121.8083,
    timezone: 'Asia/Shanghai',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'NRT',
    icao: 'RJAA',
    name: 'Narita International',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    latitude: 35.772,
    longitude: 140.3928,
    timezone: 'Asia/Tokyo',
    elevation: 141,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'HND',
    icao: 'RJTT',
    name: 'Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    latitude: 35.5494,
    longitude: 139.7798,
    timezone: 'Asia/Tokyo',
    elevation: 21,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ICN',
    icao: 'RKSI',
    name: 'Incheon International',
    city: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    latitude: 37.4602,
    longitude: 126.4407,
    timezone: 'Asia/Seoul',
    elevation: 23,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'SIN',
    icao: 'WSSS',
    name: 'Singapore Changi',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    latitude: 1.3644,
    longitude: 103.9915,
    timezone: 'Asia/Singapore',
    elevation: 22,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'HKG',
    icao: 'VHHH',
    name: 'Hong Kong International',
    city: 'Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    latitude: 22.308,
    longitude: 113.9185,
    timezone: 'Asia/Hong_Kong',
    elevation: 28,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BKK',
    icao: 'VTBS',
    name: 'Suvarnabhumi',
    city: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    latitude: 13.69,
    longitude: 100.7501,
    timezone: 'Asia/Bangkok',
    elevation: 5,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'KUL',
    icao: 'WMKK',
    name: 'Kuala Lumpur International',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'Asia',
    latitude: 2.7456,
    longitude: 101.7099,
    timezone: 'Asia/Kuala_Lumpur',
    elevation: 69,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DEL',
    icao: 'VIDP',
    name: 'Indira Gandhi International',
    city: 'Delhi',
    country: 'India',
    region: 'Asia',
    latitude: 28.5562,
    longitude: 77.1,
    timezone: 'Asia/Kolkata',
    elevation: 777,
    isActive: true,
    hubType: 'major',
  },

  // Major Middle Eastern Airports
  {
    code: 'DXB',
    icao: 'OMDB',
    name: 'Dubai International',
    city: 'Dubai',
    country: 'UAE',
    region: 'Middle East',
    latitude: 25.2532,
    longitude: 55.3657,
    timezone: 'Asia/Dubai',
    elevation: 62,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DOH',
    icao: 'OTHH',
    name: 'Hamad International',
    city: 'Doha',
    country: 'Qatar',
    region: 'Middle East',
    latitude: 25.2611,
    longitude: 51.5651,
    timezone: 'Asia/Qatar',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'IST',
    icao: 'LTFM',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Turkey',
    region: 'Middle East',
    latitude: 41.2753,
    longitude: 28.7519,
    timezone: 'Europe/Istanbul',
    elevation: 325,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'AUH',
    icao: 'OMAA',
    name: 'Abu Dhabi International',
    city: 'Abu Dhabi',
    country: 'UAE',
    region: 'Middle East',
    latitude: 24.4329,
    longitude: 54.6511,
    timezone: 'Asia/Dubai',
    elevation: 88,
    isActive: true,
    hubType: 'major',
  },

  // Major Canadian Airports
  {
    code: 'YYZ',
    icao: 'CYYZ',
    name: 'Toronto Pearson International',
    city: 'Toronto',
    country: 'Canada',
    region: 'North America',
    latitude: 43.6777,
    longitude: -79.6248,
    timezone: 'America/Toronto',
    elevation: 569,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YVR',
    icao: 'CYVR',
    name: 'Vancouver International',
    city: 'Vancouver',
    country: 'Canada',
    region: 'North America',
    latitude: 49.1967,
    longitude: -123.1815,
    timezone: 'America/Vancouver',
    elevation: 14,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YUL',
    icao: 'CYUL',
    name: 'Montreal-Pierre Elliott Trudeau International',
    city: 'Montreal',
    country: 'Canada',
    region: 'North America',
    latitude: 45.4706,
    longitude: -73.7408,
    timezone: 'America/Montreal',
    elevation: 118,
    isActive: true,
    hubType: 'major',
  },

  // Major Australian Airports
  {
    code: 'SYD',
    icao: 'YSSY',
    name: 'Sydney Kingsford Smith',
    city: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    latitude: -33.9399,
    longitude: 151.1753,
    timezone: 'Australia/Sydney',
    elevation: 21,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MEL',
    icao: 'YMML',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    latitude: -37.6733,
    longitude: 144.8433,
    timezone: 'Australia/Melbourne',
    elevation: 434,
    isActive: true,
    hubType: 'major',
  },

  // Major South American Airports
  {
    code: 'GRU',
    icao: 'SBGR',
    name: 'São Paulo-Guarulhos International',
    city: 'São Paulo',
    country: 'Brazil',
    region: 'South America',
    latitude: -23.4356,
    longitude: -46.4731,
    timezone: 'America/Sao_Paulo',
    elevation: 2459,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'EZE',
    icao: 'SAEZ',
    name: 'Ministro Pistarini International',
    city: 'Buenos Aires',
    country: 'Argentina',
    region: 'South America',
    latitude: -34.8222,
    longitude: -58.5358,
    timezone: 'America/Argentina/Buenos_Aires',
    elevation: 20,
    isActive: true,
    hubType: 'major',
  },

  // Additional major airports for comprehensive coverage
  {
    code: 'CPH',
    icao: 'EKCH',
    name: 'Copenhagen Airport',
    city: 'Copenhagen',
    country: 'Denmark',
    region: 'Europe',
    latitude: 55.6179,
    longitude: 12.656,
    timezone: 'Europe/Copenhagen',
    elevation: 17,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ARN',
    icao: 'ESSA',
    name: 'Stockholm Arlanda',
    city: 'Stockholm',
    country: 'Sweden',
    region: 'Europe',
    latitude: 59.6519,
    longitude: 17.9186,
    timezone: 'Europe/Stockholm',
    elevation: 137,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'OSL',
    icao: 'ENGM',
    name: 'Oslo Airport',
    city: 'Oslo',
    country: 'Norway',
    region: 'Europe',
    latitude: 60.1939,
    longitude: 11.1004,
    timezone: 'Europe/Oslo',
    elevation: 681,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'HEL',
    icao: 'EFHK',
    name: 'Helsinki Airport',
    city: 'Helsinki',
    country: 'Finland',
    region: 'Europe',
    latitude: 60.3172,
    longitude: 24.9633,
    timezone: 'Europe/Helsinki',
    elevation: 179,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ATH',
    icao: 'LGAV',
    name: 'Athens International',
    city: 'Athens',
    country: 'Greece',
    region: 'Europe',
    latitude: 37.9364,
    longitude: 23.9445,
    timezone: 'Europe/Athens',
    elevation: 308,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'WAW',
    icao: 'EPWA',
    name: 'Warsaw Chopin',
    city: 'Warsaw',
    country: 'Poland',
    region: 'Europe',
    latitude: 52.1657,
    longitude: 20.9671,
    timezone: 'Europe/Warsaw',
    elevation: 362,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LIS',
    icao: 'LPPT',
    name: 'Humberto Delgado',
    city: 'Lisbon',
    country: 'Portugal',
    region: 'Europe',
    latitude: 38.7813,
    longitude: -9.1359,
    timezone: 'Europe/Lisbon',
    elevation: 374,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BRU',
    icao: 'EBBR',
    name: 'Brussels Airport',
    city: 'Brussels',
    country: 'Belgium',
    region: 'Europe',
    latitude: 50.9014,
    longitude: 4.4844,
    timezone: 'Europe/Brussels',
    elevation: 184,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DUB',
    icao: 'EIDW',
    name: 'Dublin Airport',
    city: 'Dublin',
    country: 'Ireland',
    region: 'Europe',
    latitude: 53.4264,
    longitude: -6.2499,
    timezone: 'Europe/Dublin',
    elevation: 242,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MAN',
    icao: 'EGCC',
    name: 'Manchester Airport',
    city: 'Manchester',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 53.3538,
    longitude: -2.275,
    timezone: 'Europe/London',
    elevation: 257,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LGW',
    icao: 'EGKK',
    name: 'London Gatwick',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.1481,
    longitude: -0.1903,
    timezone: 'Europe/London',
    elevation: 202,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'STN',
    icao: 'EGSS',
    name: 'London Stansted',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.885,
    longitude: 0.235,
    timezone: 'Europe/London',
    elevation: 348,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LTN',
    icao: 'EGGW',
    name: 'London Luton',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.8747,
    longitude: -0.3683,
    timezone: 'Europe/London',
    elevation: 526,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BHX',
    icao: 'EGBB',
    name: 'Birmingham Airport',
    city: 'Birmingham',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 52.4539,
    longitude: -1.748,
    timezone: 'Europe/London',
    elevation: 327,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BRS',
    icao: 'EGGD',
    name: 'Bristol Airport',
    city: 'Bristol',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.3827,
    longitude: -2.7191,
    timezone: 'Europe/London',
    elevation: 622,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'NCL',
    icao: 'EGNT',
    name: 'Newcastle Airport',
    city: 'Newcastle',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 55.0375,
    longitude: -1.6917,
    timezone: 'Europe/London',
    elevation: 266,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'EDI',
    icao: 'EGPH',
    name: 'Edinburgh Airport',
    city: 'Edinburgh',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 55.95,
    longitude: -3.3725,
    timezone: 'Europe/London',
    elevation: 135,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'GLA',
    icao: 'EGPF',
    name: 'Glasgow Airport',
    city: 'Glasgow',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 55.8719,
    longitude: -4.4331,
    timezone: 'Europe/London',
    elevation: 26,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BFS',
    icao: 'EGAA',
    name: 'Belfast International',
    city: 'Belfast',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 54.6575,
    longitude: -6.2158,
    timezone: 'Europe/London',
    elevation: 268,
    isActive: true,
    hubType: 'major',
  },

  // Additional Asian airports
  {
    code: 'CAN',
    icao: 'ZGGG',
    name: 'Guangzhou Baiyun International',
    city: 'Guangzhou',
    country: 'China',
    region: 'Asia',
    latitude: 23.3924,
    longitude: 113.2988,
    timezone: 'Asia/Shanghai',
    elevation: 50,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'SZX',
    icao: 'ZGSZ',
    name: "Shenzhen Bao'an International",
    city: 'Shenzhen',
    country: 'China',
    region: 'Asia',
    latitude: 22.6392,
    longitude: 113.8108,
    timezone: 'Asia/Shanghai',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CTU',
    icao: 'ZUUU',
    name: 'Chengdu Shuangliu International',
    city: 'Chengdu',
    country: 'China',
    region: 'Asia',
    latitude: 30.5785,
    longitude: 103.9469,
    timezone: 'Asia/Shanghai',
    elevation: 1625,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'KMG',
    icao: 'ZPPP',
    name: 'Kunming Changshui International',
    city: 'Kunming',
    country: 'China',
    region: 'Asia',
    latitude: 25.1019,
    longitude: 102.9292,
    timezone: 'Asia/Shanghai',
    elevation: 6903,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'XIY',
    icao: 'ZLXY',
    name: "Xi'an Xianyang International",
    city: "Xi'an",
    country: 'China',
    region: 'Asia',
    latitude: 34.4471,
    longitude: 108.7516,
    timezone: 'Asia/Shanghai',
    elevation: 1572,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'HGH',
    icao: 'ZSHC',
    name: 'Hangzhou Xiaoshan International',
    city: 'Hangzhou',
    country: 'China',
    region: 'Asia',
    latitude: 30.2294,
    longitude: 120.4344,
    timezone: 'Asia/Shanghai',
    elevation: 23,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'NKG',
    icao: 'ZSNJ',
    name: 'Nanjing Lukou International',
    city: 'Nanjing',
    country: 'China',
    region: 'Asia',
    latitude: 31.742,
    longitude: 118.862,
    timezone: 'Asia/Shanghai',
    elevation: 49,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'TSN',
    icao: 'ZBTJ',
    name: 'Tianjin Binhai International',
    city: 'Tianjin',
    country: 'China',
    region: 'Asia',
    latitude: 39.1244,
    longitude: 117.3462,
    timezone: 'Asia/Shanghai',
    elevation: 10,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'KIX',
    icao: 'RJBB',
    name: 'Kansai International',
    city: 'Osaka',
    country: 'Japan',
    region: 'Asia',
    latitude: 34.4342,
    longitude: 135.2441,
    timezone: 'Asia/Tokyo',
    elevation: 15,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'GMP',
    icao: 'RKSS',
    name: 'Gimpo International',
    city: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    latitude: 37.5583,
    longitude: 126.7906,
    timezone: 'Asia/Seoul',
    elevation: 58,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DMK',
    icao: 'VTBD',
    name: 'Don Mueang International',
    city: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    latitude: 13.9126,
    longitude: 100.6068,
    timezone: 'Asia/Bangkok',
    elevation: 9,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CGK',
    icao: 'WIII',
    name: 'Soekarno-Hatta International',
    city: 'Jakarta',
    country: 'Indonesia',
    region: 'Asia',
    latitude: -6.1256,
    longitude: 106.6558,
    timezone: 'Asia/Jakarta',
    elevation: 32,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MNL',
    icao: 'RPLL',
    name: 'Ninoy Aquino International',
    city: 'Manila',
    country: 'Philippines',
    region: 'Asia',
    latitude: 14.5086,
    longitude: 121.0196,
    timezone: 'Asia/Manila',
    elevation: 75,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BOM',
    icao: 'VABB',
    name: 'Chhatrapati Shivaji Maharaj International',
    city: 'Mumbai',
    country: 'India',
    region: 'Asia',
    latitude: 19.0887,
    longitude: 72.8681,
    timezone: 'Asia/Kolkata',
    elevation: 39,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BLR',
    icao: 'VOBL',
    name: 'Kempegowda International',
    city: 'Bangalore',
    country: 'India',
    region: 'Asia',
    latitude: 13.1979,
    longitude: 77.7063,
    timezone: 'Asia/Kolkata',
    elevation: 3000,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CCU',
    icao: 'VECC',
    name: 'Netaji Subhash Chandra Bose International',
    city: 'Kolkata',
    country: 'India',
    region: 'Asia',
    latitude: 22.6546,
    longitude: 88.4467,
    timezone: 'Asia/Kolkata',
    elevation: 16,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'MAA',
    icao: 'VOMM',
    name: 'Chennai International',
    city: 'Chennai',
    country: 'India',
    region: 'Asia',
    latitude: 12.9941,
    longitude: 80.1709,
    timezone: 'Asia/Kolkata',
    elevation: 52,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'HYD',
    icao: 'VOHS',
    name: 'Rajiv Gandhi International',
    city: 'Hyderabad',
    country: 'India',
    region: 'Asia',
    latitude: 17.2403,
    longitude: 78.4294,
    timezone: 'Asia/Kolkata',
    elevation: 1742,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'COK',
    icao: 'VOCI',
    name: 'Cochin International',
    city: 'Kochi',
    country: 'India',
    region: 'Asia',
    latitude: 10.152,
    longitude: 76.4019,
    timezone: 'Asia/Kolkata',
    elevation: 30,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'PNQ',
    icao: 'VAPO',
    name: 'Pune Airport',
    city: 'Pune',
    country: 'India',
    region: 'Asia',
    latitude: 18.5821,
    longitude: 73.9197,
    timezone: 'Asia/Kolkata',
    elevation: 1942,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'GOI',
    icao: 'VAGO',
    name: 'Dabolim Airport',
    city: 'Goa',
    country: 'India',
    region: 'Asia',
    latitude: 15.3808,
    longitude: 73.8314,
    timezone: 'Asia/Kolkata',
    elevation: 150,
    isActive: true,
    hubType: 'major',
  },

  // Additional Middle Eastern airports
  {
    code: 'SAW',
    icao: 'LTFJ',
    name: 'Sabiha Gökçen International',
    city: 'Istanbul',
    country: 'Turkey',
    region: 'Middle East',
    latitude: 40.8986,
    longitude: 29.3092,
    timezone: 'Europe/Istanbul',
    elevation: 312,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'TLV',
    icao: 'LLBG',
    name: 'Ben Gurion Airport',
    city: 'Tel Aviv',
    country: 'Israel',
    region: 'Middle East',
    latitude: 32.0114,
    longitude: 34.8867,
    timezone: 'Asia/Jerusalem',
    elevation: 135,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'RUH',
    icao: 'OERK',
    name: 'King Khalid International',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    region: 'Middle East',
    latitude: 24.9578,
    longitude: 46.6989,
    timezone: 'Asia/Riyadh',
    elevation: 2049,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'JED',
    icao: 'OEJN',
    name: 'King Abdulaziz International',
    city: 'Jeddah',
    country: 'Saudi Arabia',
    region: 'Middle East',
    latitude: 21.6796,
    longitude: 39.1565,
    timezone: 'Asia/Riyadh',
    elevation: 48,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'KWI',
    icao: 'OKBK',
    name: 'Kuwait International',
    city: 'Kuwait City',
    country: 'Kuwait',
    region: 'Middle East',
    latitude: 29.2266,
    longitude: 47.9689,
    timezone: 'Asia/Kuwait',
    elevation: 206,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BAH',
    icao: 'OBBI',
    name: 'Bahrain International',
    city: 'Manama',
    country: 'Bahrain',
    region: 'Middle East',
    latitude: 26.2708,
    longitude: 50.6336,
    timezone: 'Asia/Bahrain',
    elevation: 6,
    isActive: true,
    hubType: 'major',
  },

  // Additional African airports
  {
    code: 'JNB',
    icao: 'FAOR',
    name: 'O.R. Tambo International',
    city: 'Johannesburg',
    country: 'South Africa',
    region: 'Africa',
    latitude: -26.1337,
    longitude: 28.2423,
    timezone: 'Africa/Johannesburg',
    elevation: 5558,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CPT',
    icao: 'FACT',
    name: 'Cape Town International',
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    latitude: -33.9648,
    longitude: 18.6017,
    timezone: 'Africa/Johannesburg',
    elevation: 151,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CAI',
    icao: 'HECA',
    name: 'Cairo International',
    city: 'Cairo',
    country: 'Egypt',
    region: 'Africa',
    latitude: 30.1219,
    longitude: 31.4056,
    timezone: 'Africa/Cairo',
    elevation: 382,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LOS',
    icao: 'DNMM',
    name: 'Murtala Muhammed International',
    city: 'Lagos',
    country: 'Nigeria',
    region: 'Africa',
    latitude: 6.5774,
    longitude: 3.3212,
    timezone: 'Africa/Lagos',
    elevation: 135,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'NBO',
    icao: 'HKJK',
    name: 'Jomo Kenyatta International',
    city: 'Nairobi',
    country: 'Kenya',
    region: 'Africa',
    latitude: -1.3192,
    longitude: 36.9278,
    timezone: 'Africa/Nairobi',
    elevation: 5317,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CMN',
    icao: 'GMMN',
    name: 'Mohammed V International',
    city: 'Casablanca',
    country: 'Morocco',
    region: 'Africa',
    latitude: 33.3675,
    longitude: -7.5899,
    timezone: 'Africa/Casablanca',
    elevation: 656,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'TUN',
    icao: 'DTTA',
    name: 'Tunis-Carthage International',
    city: 'Tunis',
    country: 'Tunisia',
    region: 'Africa',
    latitude: 36.851,
    longitude: 10.2272,
    timezone: 'Africa/Tunis',
    elevation: 22,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ALG',
    icao: 'DAAG',
    name: 'Houari Boumediene Airport',
    city: 'Algiers',
    country: 'Algeria',
    region: 'Africa',
    latitude: 36.691,
    longitude: 3.2154,
    timezone: 'Africa/Algiers',
    elevation: 82,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ADD',
    icao: 'HAAB',
    name: 'Bole International',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    region: 'Africa',
    latitude: 8.9779,
    longitude: 38.7993,
    timezone: 'Africa/Addis_Ababa',
    elevation: 7656,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DAR',
    icao: 'HTDA',
    name: 'Julius Nyerere International',
    city: 'Dar es Salaam',
    country: 'Tanzania',
    region: 'Africa',
    latitude: -6.8781,
    longitude: 39.2026,
    timezone: 'Africa/Dar_es_Salaam',
    elevation: 182,
    isActive: true,
    hubType: 'major',
  },

  // Additional Canadian airports
  {
    code: 'YYC',
    icao: 'CYYC',
    name: 'Calgary International',
    city: 'Calgary',
    country: 'Canada',
    region: 'North America',
    latitude: 51.1314,
    longitude: -114.0103,
    timezone: 'America/Edmonton',
    elevation: 3557,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YEG',
    icao: 'CYEG',
    name: 'Edmonton International',
    city: 'Edmonton',
    country: 'Canada',
    region: 'North America',
    latitude: 53.3097,
    longitude: -113.5792,
    timezone: 'America/Edmonton',
    elevation: 2373,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YOW',
    icao: 'CYOW',
    name: 'Ottawa Macdonald-Cartier International',
    city: 'Ottawa',
    country: 'Canada',
    region: 'North America',
    latitude: 45.3225,
    longitude: -75.6692,
    timezone: 'America/Toronto',
    elevation: 374,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YHZ',
    icao: 'CYHZ',
    name: 'Halifax Stanfield International',
    city: 'Halifax',
    country: 'Canada',
    region: 'North America',
    latitude: 44.8808,
    longitude: -63.5086,
    timezone: 'America/Halifax',
    elevation: 477,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'YWG',
    icao: 'CYWG',
    name: 'Winnipeg James Armstrong Richardson International',
    city: 'Winnipeg',
    country: 'Canada',
    region: 'North America',
    latitude: 49.91,
    longitude: -97.2399,
    timezone: 'America/Winnipeg',
    elevation: 783,
    isActive: true,
    hubType: 'major',
  },

  // Additional Australian airports
  {
    code: 'BNE',
    icao: 'YBBN',
    name: 'Brisbane Airport',
    city: 'Brisbane',
    country: 'Australia',
    region: 'Oceania',
    latitude: -27.3842,
    longitude: 153.1175,
    timezone: 'Australia/Brisbane',
    elevation: 13,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'PER',
    icao: 'YPPH',
    name: 'Perth Airport',
    city: 'Perth',
    country: 'Australia',
    region: 'Oceania',
    latitude: -31.9403,
    longitude: 115.9669,
    timezone: 'Australia/Perth',
    elevation: 67,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'ADL',
    icao: 'YPAD',
    name: 'Adelaide Airport',
    city: 'Adelaide',
    country: 'Australia',
    region: 'Oceania',
    latitude: -34.9455,
    longitude: 138.5306,
    timezone: 'Australia/Adelaide',
    elevation: 20,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'OOL',
    icao: 'YBCG',
    name: 'Gold Coast Airport',
    city: 'Gold Coast',
    country: 'Australia',
    region: 'Oceania',
    latitude: -28.1644,
    longitude: 153.5047,
    timezone: 'Australia/Brisbane',
    elevation: 21,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CNS',
    icao: 'YBCS',
    name: 'Cairns Airport',
    city: 'Cairns',
    country: 'Australia',
    region: 'Oceania',
    latitude: -16.8858,
    longitude: 145.7553,
    timezone: 'Australia/Brisbane',
    elevation: 10,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'DRW',
    icao: 'YPDN',
    name: 'Darwin International',
    city: 'Darwin',
    country: 'Australia',
    region: 'Oceania',
    latitude: -12.4083,
    longitude: 130.8726,
    timezone: 'Australia/Darwin',
    elevation: 103,
    isActive: true,
    hubType: 'major',
  },

  // Additional South American airports
  {
    code: 'GIG',
    icao: 'SBGL',
    name: 'Rio de Janeiro-Galeão International',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'South America',
    latitude: -22.8089,
    longitude: -43.25,
    timezone: 'America/Sao_Paulo',
    elevation: 28,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BSB',
    icao: 'SBBR',
    name: 'Brasília International',
    city: 'Brasília',
    country: 'Brazil',
    region: 'South America',
    latitude: -15.8692,
    longitude: -47.9206,
    timezone: 'America/Sao_Paulo',
    elevation: 3497,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'SCL',
    icao: 'SCEL',
    name: 'Arturo Merino Benítez International',
    city: 'Santiago',
    country: 'Chile',
    region: 'South America',
    latitude: -33.3928,
    longitude: -70.7858,
    timezone: 'America/Santiago',
    elevation: 1555,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'LIM',
    icao: 'SPIM',
    name: 'Jorge Chávez International',
    city: 'Lima',
    country: 'Peru',
    region: 'South America',
    latitude: -12.0219,
    longitude: -77.1143,
    timezone: 'America/Lima',
    elevation: 113,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'BOG',
    icao: 'SKBO',
    name: 'El Dorado International',
    city: 'Bogotá',
    country: 'Colombia',
    region: 'South America',
    latitude: 4.7016,
    longitude: -74.1469,
    timezone: 'America/Bogota',
    elevation: 8361,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'UIO',
    icao: 'SEQU',
    name: 'Mariscal Sucre International',
    city: 'Quito',
    country: 'Ecuador',
    region: 'South America',
    latitude: -0.1411,
    longitude: -78.4882,
    timezone: 'America/Guayaquil',
    elevation: 7841,
    isActive: true,
    hubType: 'major',
  },
  {
    code: 'CCS',
    icao: 'SVMI',
    name: 'Simón Bolívar International',
    city: 'Caracas',
    country: 'Venezuela',
    region: 'South America',
    latitude: 10.6031,
    longitude: -67.0058,
    timezone: 'America/Caracas',
    elevation: 2356,
    isActive: true,
    hubType: 'major',
  },

  // Additional major airports for comprehensive coverage
  {
    code: 'TPE',
    icao: 'RCTP',
    name: 'Taiwan Taoyuan International',
    city: 'Taipei',
    country: 'Taiwan',
    region: 'Asia',
    latitude: 25.0777,
    longitude: 121.2328,
    timezone: 'Asia/Taipei',
    elevation: 108,
    isActive: true,
    hubType: 'major',
  },
];

// Helper functions for airport operations
export function searchAirports(query: string): Airport[] {
  if (!query || query.length < 1) return [];

  const lowerQuery = query.toLowerCase();
  return airports
    .filter(
      (airport) =>
        airport.code.toLowerCase().includes(lowerQuery) ||
        airport.icao.toLowerCase().includes(lowerQuery) ||
        airport.name.toLowerCase().includes(lowerQuery) ||
        airport.city.toLowerCase().includes(lowerQuery) ||
        airport.country.toLowerCase().includes(lowerQuery)
    )
    .slice(0, 10); // Limit to 10 results
}

export function getAirportByCode(code: string): Airport | undefined {
  return airports.find(
    (airport) => airport.code.toLowerCase() === code.toLowerCase()
  );
}

export function getAirportByICAO(icao: string): Airport | undefined {
  return airports.find(
    (airport) => airport.icao.toLowerCase() === icao.toLowerCase()
  );
}

export function validateAirportCode(code: string): boolean {
  return airports.some(
    (airport) => airport.code.toLowerCase() === code.toLowerCase()
  );
}

export function validateAirportICAO(icao: string): boolean {
  return airports.some(
    (airport) => airport.icao.toLowerCase() === icao.toLowerCase()
  );
}

export function getAirportsByRegion(region: string): Airport[] {
  return airports.filter(
    (airport) => airport.region.toLowerCase() === region.toLowerCase()
  );
}

export function getAirportsByCountry(country: string): Airport[] {
  return airports.filter(
    (airport) => airport.country.toLowerCase() === country.toLowerCase()
  );
}

export function getAirportsByHubType(hubType: Airport['hubType']): Airport[] {
  return airports.filter((airport) => airport.hubType === hubType);
}

export function getActiveAirports(): Airport[] {
  return airports.filter((airport) => airport.isActive);
}

export function getAirportCoordinates(
  code: string
): { latitude: number; longitude: number } | null {
  const airport = getAirportByCode(code);
  if (!airport) return null;

  return {
    latitude: airport.latitude,
    longitude: airport.longitude,
  };
}

export function validateAirportExists(code: string): boolean {
  return validateAirportCode(code);
}

// Export the airports array for backward compatibility
export { airports as allAirports };
