name: Code Quality & Testing

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    quality-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install gitleaks
              run: |
                  wget https://github.com/gitleaks/gitleaks/releases/download/v8.28.0/gitleaks_8.28.0_linux_x64.tar.gz
                  tar -xzf gitleaks_8.28.0_linux_x64.tar.gz
                  sudo mv gitleaks /usr/local/bin/
                  gitleaks version

            - name: Scan for secrets
              run: npm run scan:secrets

            - name: Run ESLint
              run: npm run lint

            - name: Run TypeScript check
              run: npm run type-check

            - name: Run tests
              run: npm test

            - name: Build application
              run: npm run build

            - name: Check for security vulnerabilities
              run: npm audit --audit-level=moderate
